In [1]:

print("Họ tên: NguyenDucTinh")
print("Mã số sinh viên: 6451071077")

# Linear algebra
import numpy as np

# Data processing
import pandas as pd

# Data visualization
import seaborn as sns
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import style

# ============================================================
# a. Đọc dữ liệu và đặt tên cột
# ============================================================
# Kiểm tra: file tb_tracking.csv KHÔNG có header (dòng đầu là dữ liệu số)
# 6 cột theo thứ tự: id, device_id, co_level, humidity, temperature, time

col_names = ['id', 'device_id', 'co_level', 'humidity', 'temperature', 'time']

df = pd.read_csv(
    'tb_tracking.csv',
    header=None,          # file không có header
    names=col_names,      # gán tên cột theo thứ tự yêu cầu
    encoding='utf-8'
)

print(f"Số cột: {df.shape[1]}")
print(f"Tên cột: {list(df.columns)}")
print(f"Tổng số dòng ban đầu: {len(df)}")
df.head()

Họ tên: NguyenDucTinh
Mã số sinh viên: 6451071077
Số cột: 6
Tên cột: ['id', 'device_id', 'co_level', 'humidity', 'temperature', 'time']
Tổng số dòng ban đầu: 33336

   id  device_id  co_level  humidity  temperature                 time
0   1          1       2.0         3            4  2016-12-20 12:52:29
1   2          1       2.0         3            4  2016-12-20 12:52:31
2   3        100       2.0         3            4  2016-12-20 12:52:35
3   4        100       2.0         3          400  2016-12-20 12:52:37
4   5          1       2.0         3            4  2016-12-20 13:02:01

In [2]:
print("Họ tên: NguyenDucTinh")
print("Mã số sinh viên: 6451071077")

# Xem thông tin kiểu dữ liệu ban đầu
df.info()

Họ tên: NguyenDucTinh
Mã số sinh viên: 6451071077
<class 'pandas.DataFrame'>
RangeIndex: 33336 entries, 0 to 33335
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           33336 non-null  int64
 1   device_id    33336 non-null  int64
 2   co_level     33336 non-null  float64
 3   humidity     33336 non-null  int64
 4   temperature  33336 non-null  int64
 5   time         33336 non-null  str
dtypes: float64(1), int64(4), str(1)
memory usage: 1.5 MB

In [3]:
print("Họ tên: NguyenDucTinh")
print("Mã số sinh viên: 6451071077")

# ============================================================
# b. Lọc thời gian: giữ dữ liệu từ ngày 03/01/2018 trở đi
# (tức ngày 3 tháng 1 năm 2018)
# ============================================================

# Chuyển cột time sang kiểu datetime
df['time'] = pd.to_datetime(df['time'])

so_dong_truoc = len(df)
print(f"Số dòng TRƯỚC khi lọc: {so_dong_truoc}")

# Loại bỏ dữ liệu trước ngày 03/01/2018
ngay_gioi_han = pd.Timestamp('2018-01-03')
df = df[df['time'] >= ngay_gioi_han]

so_dong_sau = len(df)
print(f"Số dòng SAU khi lọc (từ 03/01/2018 trở đi): {so_dong_sau}")
print(f"Số dòng đã loại bỏ: {so_dong_truoc - so_dong_sau}")
df.head()

Họ tên: NguyenDucTinh
Mã số sinh viên: 6451071077
Số dòng TRƯỚC khi lọc: 33336
Số dòng SAU khi lọc (từ 03/01/2018 trở đi): 1917
Số dòng đã loại bỏ: 31419

          id  device_id  co_level  humidity  temperature                time
31419  31420          1       2.0         3            4 2018-01-03 13:11:07
31420  31421          1       2.0         3            4 2018-01-03 13:15:10
31421  31422      99005      58.0        26            0 2018-01-03 13:17:30
31422  31423      99005      58.0        26            0 2018-01-03 13:19:21
31423  31424      99005      58.0        26            0 2018-01-03 13:24:17

In [4]:
print("Họ tên: NguyenDucTinh")
print("Mã số sinh viên: 6451071077")

# ============================================================
# c. Tạo cột minutes = giờ * 60 + phút
# Ví dụ: 08:30 -> 510, 12:45 -> 765
# ============================================================

df['minutes'] = df['time'].dt.hour * 60 + df['time'].dt.minute

print("Cột minutes đã được tạo.")
print(f"Ví dụ: giờ 8:30 -> {8*60+30} phút | 12:45 -> {12*60+45} phút")
df[['time', 'minutes']].head(10)

Họ tên: NguyenDucTinh
Mã số sinh viên: 6451071077
Cột minutes đã được tạo.
Ví dụ: giờ 8:30 -> 510 phút | 12:45 -> 765 phút

                     time  minutes
31419 2018-01-03 13:11:07      791
31420 2018-01-03 13:15:10      795
31421 2018-01-03 13:17:30      797
31422 2018-01-03 13:19:21      799
31423 2018-01-03 13:24:17      804
31424 2018-01-03 13:29:13      809
31425 2018-01-03 13:34:10      814
31426 2018-01-03 14:05:34      845
31427 2018-01-03 14:10:43      850
31428 2018-01-03 14:15:39      855

In [5]:
print("Họ tên: NguyenDucTinh")
print("Mã số sinh viên: 6451071077")

# ============================================================
# Lưu dataset đã xử lý thành file mới (không ghi đè gốc)
# ============================================================

output_file = 'tb_tracking_processed.csv'
df.to_csv(output_file, index=False, encoding='utf-8')
print(f"Dataset đã xử lý được lưu vào: {output_file}")
print(f"Số dòng: {len(df)}, Số cột: {df.shape[1]}")
print(f"Cột: {list(df.columns)}")
df.describe()

Họ tên: NguyenDucTinh
Mã số sinh viên: 6451071077
Dataset đã xử lý được lưu vào: tb_tracking_processed.csv
Số dòng: 1917, Số cột: 7
Cột: ['id', 'device_id', 'co_level', 'humidity', 'temperature', 'time', 'minutes']

,id,device_id,co_level,humidity,temperature,time,minutes
count,1917.000000,1917.000000,1917.000000,1917.000000,1.917000e+03,1917,1917.000000
mean,32378.000000,88985.715702,28.190662,68.992697,2.358965e+06,2018-01-08 20:01:03.683881,709.297861
min,31420.000000,0.000000,2.000000,3.000000,0.000000e+00,2018-01-03 13:11:07,1.000000
25%,31899.000000,99005.000000,27.000000,61.000000,2.124650e+06,2018-01-05 11:46:41,396.000000
50%,32378.000000,99005.000000,28.000000,70.000000,2.331120e+06,2018-01-09 00:38:28,713.000000
75%,32857.000000,99005.000000,28.000000,79.000000,2.570550e+06,2018-01-11 11:52:31,993.000000
max,33336.000000,99005.000000,77.000000,86.000000,5.340310e+06,2018-01-17 15:46:34,1439.000000
std,553.534552,29867.012091,3.997557,12.033094,4.951416e+05,NaN,391.934697